#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""zp12's factory kit: the 16 CC0 drum hits of assets/samples-cc0/KIT (SLOOP's built-in set, CC0 1.0),
cut to a length that fits, faded, resampled to 12 bit at 26.04 kHz and packed (2 samples in 3 bytes),
as build/gen/zp12_kit.h: the waves, and the 32 pads' default sounds (bank A and B the kit, C a dirtier
copy an octave lower at 45->33, D bank A reversed and tuned).

  tools/gen_kit.py build/gen/zp12_kit.h

The resampler is the one of tests/sp_core_test.c and the web editor: a Hann-windowed sinc low-pass at 0.45 of
the lower rate (a sampler's input filter), then 12 bit rounded."""
import math
import sys
import wave
from pathlib import Path

import numpy as np

KIT = Path(__file__).resolve().parents[1] / "assets" / "samples-cc0" / "KIT"
RATE = 26040
# name, file, seconds kept, channel (0..7), decay, level, pan, cut, reso
SOUNDS = [
    ("KICK", "10_kick_BDrumNew_hit_v5.wav", 0.55, 0, 110, 127, 0, 127, 0),
    ("SNARE", "11_snare_Snare2_HitSN_v7.wav", 0.38, 1, 100, 118, 0, 127, 0),
    ("RIM", "12_rim_sidestick.wav", 0.16, 5, 90, 100, -10, 127, 0),
    ("CLAP", "13_clap_Clap_rr1.wav", 0.40, 3, 95, 110, 6, 127, 0),
    ("HAT", "14_hihat_HitC_v3.wav", 0.16, 2, 60, 90, 18, 127, 0),
    ("OHAT", "15_ohat_HitO.wav", 0.55, 2, 100, 84, 18, 127, 0),       # (channel 3 with HAT: it chokes it)
    ("TOM L", "16_tomlo_TomL_HitS_v4.wav", 0.42, 4, 100, 112, -16, 127, 0),
    ("TOM H", "17_tomhi_TomH_HitS_v4.wav", 0.38, 4, 100, 108, 16, 127, 0),
    ("CRASH", "18_crash_susCymb2_hit_f1.wav", 0.75, 6, 110, 80, -20, 127, 0),
    ("RIDE", "19_ride_susCymb2_stick_mf1.wav", 0.55, 6, 110, 76, 20, 127, 0),
    ("COWBL", "20_cowbell_Cowbell1_Normal_v3.wav", 0.26, 7, 100, 90, 10, 127, 0),
    ("TAMB", "00_Tamb1_Hit_v2_rr1_Mid.wav", 0.26, 7, 100, 84, -12, 127, 0),
    ("SHAKR", "01_Mid_ShakerDouble_Down_rr1.wav", 0.26, 7, 100, 80, 14, 127, 0),
    ("CONGA", "02_Conga_HitN_v2_rr1_Sum.wav", 0.32, 5, 100, 100, -14, 127, 0),
    ("CLAVE", "03_Claves1_Hit_v2_rr1_Mid.wav", 0.16, 5, 100, 90, 12, 127, 0),
    ("WOOD", "04_wood_click_mp.wav", 0.16, 5, 100, 90, -6, 127, 0),
]


def read(path):
    with wave.open(str(path)) as w:
        n, ch, sw, r = w.getnframes(), w.getnchannels(), w.getsampwidth(), w.getframerate()
        b = w.readframes(n)
    if sw == 3:                                         # 24 bit: little-endian triplets, sign from the top byte
        u = np.frombuffer(b, dtype=np.uint8).reshape(-1, 3).astype(np.int32)
        raw = (u[:, 0] | u[:, 1] << 8 | u[:, 2] << 16)
        raw = np.where(raw & 0x800000, raw - 0x1000000, raw).astype(np.float64) / 8388608.0
    else:
        raw = np.frombuffer(b, dtype={1: np.uint8, 2: np.int16, 4: np.int32}[sw]).astype(np.float64)
        raw = (raw - 128) / 128.0 if sw == 1 else raw / (32768.0 if sw == 2 else 2147483648.0)
    return raw.reshape(-1, ch).mean(1), r


def resample12(x, src, dst):
    """as tests/sp_core_test.c resample12 (vectorised; the editor's must equal the C one, this kit need not)"""
    H = 24
    fc = 0.45 * min(src, dst) / src
    ratio = src / dst
    k = len(x) * dst // src
    span = math.ceil(H * ratio)
    t = np.arange(k) * ratio
    c = np.floor(t).astype(np.int64)
    out = np.zeros(k)
    wsum = np.zeros(k)
    for j in range(-span + 1, span + 1):
        idx = c + j
        d = t - idx
        a = 2.0 * fc * d
        sinc = np.where(a == 0, 1.0, np.sin(np.pi * a) / np.where(a == 0, 1, np.pi * a))
        g = 2.0 * fc * sinc * (0.5 + 0.5 * np.cos(np.pi * d / (span + 1)))
        ok = (idx >= 0) & (idx < len(x))
        out += np.where(ok, x[np.clip(idx, 0, len(x) - 1)], 0.0) * g
        wsum += g
    s = np.clip(np.rint(out / wsum * 2047.0), -2048, 2047).astype(np.int64)
    return s


def pack(s):
    s = [int(v) & 0xFFF for v in s]
    if len(s) & 1:
        s.append(0)
    out = bytearray()
    for i in range(0, len(s), 2):
        a, b = s[i], s[i + 1]
        out += bytes((a & 255, (a >> 8) | ((b << 4) & 0xF0), b >> 4))
    return out


def main(dst):
    blobs, waves = bytearray(), []
    for name, f, secs, *_ in SOUNDS:
        x, r = read(KIT / f)
        x = x[:int(secs * r)]
        fade = max(1, len(x) // 6)
        x[-fade:] *= np.linspace(1, 0, fade)
        peak = np.abs(x).max()
        if peak > 0:
            x = x * (0.95 / peak)                          # every hit at the same peak: the levels set the mix
        s = resample12(x, r, RATE)
        waves.append((len(blobs), len(s), name))
        blobs += pack(s)
        while len(blobs) % 4:
            blobs.append(0)
    rows = ",\n".join(",".join(str(b) for b in blobs[i:i + 32]) for i in range(0, len(blobs), 32))
    lines = [f"/* generated by tools/gen_kit.py: the CC0 kit (assets/samples-cc0/KIT), 12 bit at {RATE} Hz */",
             f"#define KIT_NWAVE {len(waves)}",
             f"#define KIT_BYTES {len(blobs)}",
             "static const uint8_t KIT_DATA[] __attribute__((aligned(4))) = {", rows, "};",
             "static const struct { uint32_t off, n; const char *name; } KIT_WAVE[KIT_NWAVE] = {"]
    lines += [f'    {{{o}, {n}, "{nm}"}},' for o, n, nm in waves]
    lines += ["};", "/* the 32 pads: wave, tune, fine, decay, level, pan, chan, flags, start, end, cut, reso */",
              "static const sp_sound_t KIT_PADS[32] = {"]
    pads = []
    for i, (name, f, secs, ch, dec, lvl, pan, cut, res) in enumerate(SOUNDS):
        pads.append((i, 0, 0, dec, lvl, pan, ch, 0, 0, 1000, cut, res))
    for i in range(8):                                 # C: bank A an octave down at 45->33, the filter on ch 1-2
        name, f, secs, ch, dec, lvl, pan, cut, res = SOUNDS[i]
        pads.append((i, -7, 0, min(127, dec + 10), lvl, pan, ch, 2, 0, 1000, 90 if ch < 2 else 127, 40 if ch < 2 else 0))
    for i in range(8):                                 # D: bank A reversed, up a fourth
        name, f, secs, ch, dec, lvl, pan, cut, res = SOUNDS[i]
        pads.append((i, 5, 0, 127, lvl - 10, -pan, ch, 1, 0, 1000, cut, res))
    lines += ["    {%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d}," % p for p in pads]
    lines += ["};", ""]
    Path(dst).parent.mkdir(parents=True, exist_ok=True)
    Path(dst).write_text("\n".join(lines))
    secs = sum(n for _, n, _ in waves) / RATE
    print(f"kit: {len(waves)} waves, {secs:.2f} s, {len(blobs)} B")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "build/gen/zp12_kit.h")
